name: ${project.name}
author: TrueMB
version: ${project.version}
api-version: 1.16
main: _me.truemb.universal.minecraft.main.BukkitMain
softdepend: [Vault, Spicord]

commands:
     dchat:
         description: Join or Leave the Discord Chat
     staff:
         description: Send messages to the Staff Team and on the Staff DC Channel
         aliases: [s]